import type { Metadata } from "next";
import { Raleway, Ubuntu } from "next/font/google";
import "./globals.css";
import {motion} from "framer-motion"; 
import {ReactNode} from "react";
const raleWay = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const uBuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleWay.variable} ${uBuntu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
